# Generated by Django 2.2.7 on 2020-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apk', '0003_donationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
