# Generated by Django 2.2.7 on 2020-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apk', '0004_donationmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
