# Generated by Django 2.2.7 on 2020-03-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apk', '0006_donationmodel_last_mod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationmodel',
            old_name='last_mod',
            new_name='created',
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
